version: 1.0.{build}
build:
  verbosity: minimal
install:
  - ps: >-
      Start-FileDownload "https://s3.amazonaws.com/rebar3/rebar3" -FileName rebar3

      $env:Path += ";${pwd}"
test_script:
  - ps: >-
      .\bin\fetch-configlet
      .\bin\configlet .
      .\rebar3 compile
      .\_build\default\lib\lfe\bin\lfe .\bin\check-exercises.lfe
