version: 1.0.{build}
install:
- cmd: >-
    git clone -q https://github.com/rebar/rebar3.git %APPVEYOR_BUILD_FOLDER%\bin\rebar3

    cd %APPVEYOR_BUILD_FOLDER%\bin\rebar3

    .\bootstrap.bat

    cd %APPVEYOR_BUILD_FOLDER%

    curl -fsSL -o configlet.zip https://github.com/exercism/configlet/releases/download/v1.0.6/configlet-windows-32bit.zip

    7z e configlet.zip

    .\configlet.exe .
build: off
test_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    %APPVEYOR_BUILD_FOLDER%\bin\rebar3\rebar3.cmd eunit -m accumulate-tests,allergies-tests,anagram-tests,atbash-cipher-tests,bank-account-tests,beer-song-tests,binary-string-tests,bob-tests,circular-buffer-tests,clock-tests,difference-of-squares-tests,etl-tests,gigasecond-tests,grade-school-tests,grains-tests,hamming-tests,largest-series-product-tests,leap-tests,luhn-tests,meetup-tests,dna-tests,parallel-letter-frequency-tests,phone-tests,rna-transcription-tests,robot-simulator-tests,series-tests,space-age-tests,strain-tests,sum-of-multiples-tests,trinary-tests,word-count-tests
