name: LFE Test

on:
  push:
  pull_request:

jobs:
  create_otp_matrix:
    name: Generate a list of last OTP versions
    runs-on: ubuntu-22.04
    outputs:
      otps: ${{ steps.versions.outputs.versions }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Get latest OTP versions
        id: versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          all_versions=$(gh api graphql -f query='query { repository(owner: "erlang", name: "otp") { releases(last: 100, orderBy: {field: CREATED_AT, direction: ASC}) { nodes { tagName } } } }' --jq '.data.repository.releases.nodes[].tagName | select(. | contains("rc") | not) | .[4:8]' | sort -u -n)
          latest_versions=$(./bin/get_latest_majors_for_ci_matrix.py <<< "$all_versions")
          echo "::set-output name=versions::$latest_versions"

  test_lfe:
    name: Test examples against OTP ${{ matrix.otp }}
    runs-on: ubuntu-22.04
    needs: create_otp_matrix
    strategy:
      matrix:
        otp: ${{fromJson(needs.create_otp_matrix.outputs.otps)}}
    container:
      image: erlang:${{ matrix.otp }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Erlang version check
        run: erl -noshell -eval 'erlang:display(erlang:system_info(system_version))' -eval 'init:stop()'
      - name: Rebar version check
        run: rebar3 -v 
      - name: Compile (with make)
        run: make compile
