# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/verify-exercises

name: Verify Exercises

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

  
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y erlang git make

      - name: Install rebar3
        run: |
          git clone https://github.com/erlang/rebar3.git
          cd rebar3
          ./bootstrap
          cd ..

      - name: Install LFE
        run: |
          git clone https://github.com/lfe/lfe.git
          cd lfe
          sudo make install

      - name: Verify all exercises
        run: bin/verify-exercises